### ISSUE TITLE
Complete front-end

### ISSUE THREAD

**Issue by sudo-chmod** [sudo-chmod/SAP-B19#2]
Need to implement 2 web pages using React.js

1st page:
    Students can enter the index number and NIC number

2nd page:
    Students can watch their academic performance including GPA and rank
    Need to implement a table with 5 fields:
        1. Subject Code
        2. Subject Name
        3. Subject Credit
        4. Subject Grade 
        5. Credit X Grade value
    The last raw should show total credit and total credit x grade values
    Mathematic functions are NOT required.
    All necessary data can be retrieved from the back-end API (credit X grade values, total credit, total credit X grade value, GPA, rank)

**Comment by IsuriCS** [comment]
Completed
